package it.polimi.Characters;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import it.polimi.Abstract.Character;
import it.polimi.Constants.Era;
import it.polimi.Constants.CharacterType;
import it.polimi.Constants.Position;

/**
 * Represents a Builder character in the game.
 * Builders are specialized characters that provide resource discounts for constructing buildings
 * and award prestige points to the player.
 */
public class Builder extends Character {


    private final int discount;
    private final int points;

    /**
     * Constructs a Builder character with the specified properties.
     *
     * @param era the era during which this character is available
     * @param players the minimum number of players required for this character to be in the deck
     * @param discount the amount of resource discount provided for building construction
     * @param points the prestige points awarded by this character
     */
    @JsonCreator
    public Builder(
            @JsonProperty("era") Era era,
            @JsonProperty("players") int players,
            @JsonProperty("discount") int discount,
            @JsonProperty("points") int points
    ) {
        super(era, players, Position.DECK, CharacterType.BUILDER);
        this.discount = discount;
        this.points = points;
    }

    /**
     * Returns the resource discount granted by this Builder for constructing buildings.
     *
     * @return the building discount value
     */
    public int getDiscount() {
        return discount;
    }

    /**
     * Returns the prestige points granted by this Builder to the player's total.
     *
     * @return the number of prestige points
     */
    public int getPoints() {
        return points;
    }

    /**
     * Returns the prestige points generated by this Builder.
     * This implementation returns the points value specific to the Builder.
     *
     * @return The prestige points.
     */
    @Override
    public int getPrestigePoints() {
        return points;
    }
}